name: Test Pipeline

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Lint with Detekt
        run: ./gradlew detekt

      - name: Build with Gradle
        run: ./gradlew buildDebug

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: TestCICD.apk
          path: app/build/outputs/apk/debug/
          
