name: Test Pipeline

on:
  push:
    branches: [ $defualt-branch ]
  pull_request:
    branches: [ $defualt-branch ]
jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint with Detekt
        run: ./gradlew detekt
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Build code base
    runs-on: ubuntu-latest
    steps:
      - name: Build with Gradle
        run: ./gradlew build
