name: Test Pipeline

on: [ push, pull_request ]

jobs:
  build:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0

      - name: Lint with Detekt
        run: ./gradlew detekt
        
      - name: Build with Gradle
        run: ./gradlew build
