name: Main PR Pipeline

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    name: Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Lint with Detekt
        run: ./gradlew detekt

      - name: Build with Gradle
        run: ./gradlew buildDebug

      - name: Run Unit Tests
        run: ./gradlew app:testDebugUnitTest
        
      - name: Assemble APK
        run: ./gradlew app:assembleDebug

      - name: List APK files
        run: ls -R app/build/outputs/apk/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: TestCICD.apk
          path: app/build/outputs/apk/debug/
          
