name: Nightly UI Tests

on:
  # schedule:
    # - cron: '0 0 * * *' # run at 12 AM UTC
  workflow_dispatch: # Allow manually triggering

jobs:
  build:
    name: UI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: |
            ./gradlew assembleDebug
            ./gradlew assembleAndroidTest
            adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
            sleep 30
            # adb shell input keyevent 82
            ./gradlew connectedDebugAndroidTest
