name: Create & Release Bundle to PlayStore

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      signing_key: ${{ secrets.SIGNING_KEY }}
      alias: ${{ secrets.SIGNING_KEY_ALIAS }}
      store_pass: ${{ secrets.SIGNING_STORE_PASSWORD }}
      key_pass: ${{ secrets.SIGNING_KEY_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Increment version of project
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts 
          versionCode: ${{github.run_number}}
          versionName: 1.0.1

      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleRelease

      - if: ${{ env.signing_key != '' }}
        run: echo 'Check 1'
      - if: ${{ env.alias != '' }}
        run: echo 'Check 2'
      - if: ${{ env.store_pass != '' }}
        run: echo 'Check 3'
      - if: ${{ env.key_pass != '' }}
        run: echo 'Check 4'

      - name: Sign AAB
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ env.signing_key }}
          alias: ${{ env.alias }}
          keyStorePassword: ${{ env.store_pass }}
          keyPassword: ${{ env.key_pass }}

      - name: Upload Bundle to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
          packageName: com.joshbogin.testCICD
          releaseFiles: ${{ steps.sign_app.outputs.signedReleaseFile }}
          track: internal
          status: draft
      
